import {useEffect,useRef,useState} from 'react'
import {Routes,Route,Link,useNavigate,useParams} from 'react-router-dom'
import {Check,Clipboard,FileAudio,History,LoaderCircle,Moon,Search,Sun,Trash2,UploadCloud} from 'lucide-react'
import {jsPDF} from 'jspdf'
import api from './api/client'

function Layout({dark,setDark,children}){return <div className={dark?'app dark':'app'}><header><Link className="brand" to="/"><span>MM</span>MeetingMind</Link><nav><Link to="/">Upload</Link><Link to="/history"><History size={17}/>History</Link><button className="icon" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button></nav></header><main>{children}</main></div>}
function ErrorBox({error}){return error?<div className="error">{error}</div>:null}
function UploadPage(){const nav=useNavigate();const input=useRef();const [file,setFile]=useState();const [title,setTitle]=useState('');const [drag,setDrag]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 const choose=f=>{if(f){setFile(f);setTitle(t=>t||f.name.replace(/\.[^.]+$/,''))}}; const submit=async()=>{if(!file||!title.trim())return setError('Choose a file and enter a title.');setLoading(true);setError('');try{const data=new FormData();data.append('title',title);data.append('file',file);const r=await api.post('/upload',data);nav(`/meeting/${r.data.id}`)}catch(e){setError(e.response?.data?.detail||e.message)}finally{setLoading(false)}};
 return <section className="hero"><div className="eyebrow">MEETING INTELLIGENCE, SIMPLIFIED</div><h1>Turn conversations into<br/><em>clear next steps.</em></h1><p>Upload a recording or transcript. MeetingMind creates a focused summary and maps every commitment.</p><div className="upload-card"><label>Meeting title</label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Weekly product sync"/><div className={`drop ${drag?'active':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);choose(e.dataTransfer.files[0])}} onClick={()=>input.current.click()}><input ref={input} hidden type="file" accept=".mp3,.wav,.mp4,.txt" onChange={e=>choose(e.target.files[0])}/><UploadCloud size={38}/><strong>{file?file.name:'Drop your meeting file here'}</strong><span>or click to browse · MP3, WAV, MP4, TXT</span></div><ErrorBox error={error}/><button className="primary" disabled={loading} onClick={submit}>{loading?<><LoaderCircle className="spin"/>Analyzing meeting…</>:<><FileAudio/>Generate insights</>}</button></div></section>}
function HistoryPage(){const [items,setItems]=useState([]);const [q,setQ]=useState('');const [error,setError]=useState('');useEffect(()=>{const t=setTimeout(()=>api.get('/meetings',{params:{search:q||undefined}}).then(r=>setItems(r.data)).catch(e=>setError(e.message)),250);return()=>clearTimeout(t)},[q]);const remove=async(id)=>{await api.delete(`/meeting/${id}`);setItems(x=>x.filter(m=>m.id!==id))};return <section><div className="page-title"><div><div className="eyebrow">YOUR KNOWLEDGE BASE</div><h1>Meeting history</h1></div><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search meetings…"/></div></div><ErrorBox error={error}/><div className="meeting-grid">{items.map(m=><article className="meeting-card" key={m.id}><Link to={`/meeting/${m.id}`}><small>{new Date(m.upload_date).toLocaleDateString()}</small><h2>{m.title}</h2><p>{m.summary}</p><span>{m.task_count} action items →</span></Link><button className="delete" onClick={()=>remove(m.id)} aria-label="Delete"><Trash2/></button></article>)}</div>{!items.length&&!error&&<div className="empty">No meetings found.</div>}</section>}
const priorityClass=p=>`pill ${p?.toLowerCase()}`;
function MeetingPage(){const {id}=useParams();const [meeting,setMeeting]=useState();const [owner,setOwner]=useState('All');const [error,setError]=useState('');useEffect(()=>{api.get(`/meeting/${id}`).then(r=>setMeeting(r.data)).catch(e=>setError(e.response?.data?.detail||e.message))},[id]);if(error)return <ErrorBox error={error}/>;if(!meeting)return <div className="loading"><LoaderCircle className="spin"/>Loading insights…</div>;const owners=['All',...new Set(meeting.tasks.map(t=>t.owner).filter(Boolean))];const tasks=meeting.tasks.filter(t=>owner==='All'||t.owner===owner);const toggle=async t=>{const r=await api.patch(`/tasks/${t.id}`,{completed:!t.completed});setMeeting(m=>({...m,tasks:m.tasks.map(x=>x.id===t.id?r.data:x)}))};const copy=()=>navigator.clipboard.writeText(meeting.summary);const pdf=()=>{const doc=new jsPDF();doc.setFontSize(20);doc.text(meeting.title,18,22);doc.setFontSize(11);doc.text(doc.splitTextToSize(meeting.summary,174),18,34);let y=70;meeting.tasks.forEach((t,i)=>{if(y>270){doc.addPage();y=20}doc.text(`${i+1}. ${t.task}`,18,y,{maxWidth:170});y+=14});doc.save(`${meeting.title}.pdf`)};
 return <section><div className="page-title"><div><div className="eyebrow">MEETING BRIEF</div><h1>{meeting.title}</h1><p>{new Date(meeting.upload_date).toLocaleString()}</p></div><button className="secondary" onClick={pdf}>Download PDF</button></div><div className="summary-card"><div className="card-heading"><h2>Executive summary</h2><button className="icon" onClick={copy} title="Copy summary"><Clipboard/></button></div><p>{meeting.summary}</p></div><div className="task-section"><div className="card-heading"><div><h2>Action items</h2><span>{meeting.tasks.filter(t=>t.completed).length} of {meeting.tasks.length} complete</span></div><select value={owner} onChange={e=>setOwner(e.target.value)}>{owners.map(o=><option key={o}>{o}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Status</th><th>Task</th><th>Owner</th><th>Deadline</th><th>Priority</th></tr></thead><tbody>{tasks.map(t=><tr key={t.id} className={t.completed?'done':''}><td><button className="check" onClick={()=>toggle(t)}>{t.completed&&<Check/>}</button></td><td>{t.task}</td><td>{t.owner||'Unassigned'}</td><td>{t.deadline||'Not set'}</td><td><span className={priorityClass(t.priority)}>{t.priority}</span></td></tr>)}</tbody></table>{!tasks.length&&<div className="empty">No action items detected.</div>}</div></div></section>}
export default function App(){const [dark,setDark]=useState(()=>localStorage.theme==='dark');useEffect(()=>{localStorage.theme=dark?'dark':'light'},[dark]);return <Layout dark={dark} setDark={setDark}><Routes><Route path="/" element={<UploadPage/>}/><Route path="/history" element={<HistoryPage/>}/><Route path="/meeting/:id" element={<MeetingPage/>}/></Routes></Layout>}
